import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, React, Tailwind CSS, SEO, Web Development",
  robots: "index, follow",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://your-website.com",
    siteName: "Your Site Name",
    images: [
      {
        url: "/path-to-your-image.jpg",
        width: 1200,
        height: 630,
        alt: "Open Graph Image",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@your-twitter-handle",
    title: "Create Next App",
    description: "Generated by create next app",
    images: [
      "/path-to-your-twitter-image.jpg",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add custom meta tag for author */}
        <meta name="author" content="Your Name or Company" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >{children}
      </body>
    </html>
  );
}
